# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import core_pb2 as core__pb2


class TemporalCoreStub(object):
  """TemporalCore implements non-specific Temporal APIs such systems checks,
  statistics, etc.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Status = channel.unary_unary(
        '/core.TemporalCore/Status',
        request_serializer=core__pb2.Empty.SerializeToString,
        response_deserializer=core__pb2.ServiceStatus.FromString,
        )
    self.Statistics = channel.unary_unary(
        '/core.TemporalCore/Statistics',
        request_serializer=core__pb2.Empty.SerializeToString,
        response_deserializer=core__pb2.ServiceStatistics.FromString,
        )


class TemporalCoreServicer(object):
  """TemporalCore implements non-specific Temporal APIs such systems checks,
  statistics, etc.
  """

  def Status(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Statistics(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TemporalCoreServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Status': grpc.unary_unary_rpc_method_handler(
          servicer.Status,
          request_deserializer=core__pb2.Empty.FromString,
          response_serializer=core__pb2.ServiceStatus.SerializeToString,
      ),
      'Statistics': grpc.unary_unary_rpc_method_handler(
          servicer.Statistics,
          request_deserializer=core__pb2.Empty.FromString,
          response_serializer=core__pb2.ServiceStatistics.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'core.TemporalCore', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
