# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ipfs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ipfs.proto',
  package='ipfs',
  syntax='proto3',
  serialized_options=_b('\n\023cloud.temporal.ipfs'),
  serialized_pb=_b('\n\nipfs.proto\x12\x04ipfs\x1a\x1cgoogle/api/annotations.proto\"\x07\n\x05\x45mpty\"m\n\x10\x43reateNetworkReq\x12\x1e\n\x07network\x18\x01 \x01(\x0b\x32\r.ipfs.Network\x12\x11\n\tswarm_key\x18\x02 \x01(\t\x12\x17\n\x0f\x62ootstrap_peers\x18\x03 \x03(\t\x12\r\n\x05users\x18\x04 \x03(\t\"\x17\n\x07Network\x12\x0c\n\x04name\x18\x01 \x01(\t\".\n\x0bNetworkList\x12\x1f\n\x08networks\x18\x01 \x03(\x0b\x32\r.ipfs.Network\"\x96\x01\n\x0eNetworkDetails\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\ncreated_at\x18\x02 \x01(\x03\x12\x12\n\ndeleted_at\x18\x03 \x01(\x03\x12\x11\n\tactivated\x18\x04 \x01(\x03\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x11\n\tswarm_key\x18\x06 \x01(\t\x12\r\n\x05users\x18\x07 \x03(\t\x12\r\n\x05peers\x18\x08 \x03(\t2\xf8\x03\n\x0cTemporalIPFS\x12_\n\rCreateNetwork\x12\x16.ipfs.CreateNetworkReq\x1a\x14.ipfs.NetworkDetails\" \x82\xd3\xe4\x93\x02\x1a\"\x18/v3/ipfs/networks/create\x12K\n\x0cStartNetwork\x12\r.ipfs.Network\x1a\x0b.ipfs.Empty\"\x1f\x82\xd3\xe4\x93\x02\x19\"\x17/v3/ipfs/networks/start\x12I\n\x0bStopNetwork\x12\r.ipfs.Network\x1a\x0b.ipfs.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18\"\x16/v3/ipfs/networks/stop\x12K\n\rRemoveNetwork\x12\r.ipfs.Network\x1a\x0b.ipfs.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18\"\x16/v3/ipfs/networks/stop\x12R\n\x0bNetworkInfo\x12\r.ipfs.Network\x1a\x14.ipfs.NetworkDetails\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v3/ipfs/networks/stat\x12N\n\x0cListNetworks\x12\x0b.ipfs.Empty\x1a\x11.ipfs.NetworkList\"\x1e\x82\xd3\xe4\x93\x02\x18\"\x16/v3/ipfs/networks/listB\x15\n\x13\x63loud.temporal.ipfsb\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='ipfs.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=57,
)


_CREATENETWORKREQ = _descriptor.Descriptor(
  name='CreateNetworkReq',
  full_name='ipfs.CreateNetworkReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='network', full_name='ipfs.CreateNetworkReq.network', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='swarm_key', full_name='ipfs.CreateNetworkReq.swarm_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bootstrap_peers', full_name='ipfs.CreateNetworkReq.bootstrap_peers', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='users', full_name='ipfs.CreateNetworkReq.users', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=168,
)


_NETWORK = _descriptor.Descriptor(
  name='Network',
  full_name='ipfs.Network',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ipfs.Network.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=193,
)


_NETWORKLIST = _descriptor.Descriptor(
  name='NetworkList',
  full_name='ipfs.NetworkList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='networks', full_name='ipfs.NetworkList.networks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=241,
)


_NETWORKDETAILS = _descriptor.Descriptor(
  name='NetworkDetails',
  full_name='ipfs.NetworkDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ipfs.NetworkDetails.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='ipfs.NetworkDetails.created_at', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deleted_at', full_name='ipfs.NetworkDetails.deleted_at', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activated', full_name='ipfs.NetworkDetails.activated', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ipfs.NetworkDetails.name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='swarm_key', full_name='ipfs.NetworkDetails.swarm_key', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='users', full_name='ipfs.NetworkDetails.users', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='peers', full_name='ipfs.NetworkDetails.peers', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=394,
)

_CREATENETWORKREQ.fields_by_name['network'].message_type = _NETWORK
_NETWORKLIST.fields_by_name['networks'].message_type = _NETWORK
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['CreateNetworkReq'] = _CREATENETWORKREQ
DESCRIPTOR.message_types_by_name['Network'] = _NETWORK
DESCRIPTOR.message_types_by_name['NetworkList'] = _NETWORKLIST
DESCRIPTOR.message_types_by_name['NetworkDetails'] = _NETWORKDETAILS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'ipfs_pb2'
  # @@protoc_insertion_point(class_scope:ipfs.Empty)
  ))
_sym_db.RegisterMessage(Empty)

CreateNetworkReq = _reflection.GeneratedProtocolMessageType('CreateNetworkReq', (_message.Message,), dict(
  DESCRIPTOR = _CREATENETWORKREQ,
  __module__ = 'ipfs_pb2'
  # @@protoc_insertion_point(class_scope:ipfs.CreateNetworkReq)
  ))
_sym_db.RegisterMessage(CreateNetworkReq)

Network = _reflection.GeneratedProtocolMessageType('Network', (_message.Message,), dict(
  DESCRIPTOR = _NETWORK,
  __module__ = 'ipfs_pb2'
  # @@protoc_insertion_point(class_scope:ipfs.Network)
  ))
_sym_db.RegisterMessage(Network)

NetworkList = _reflection.GeneratedProtocolMessageType('NetworkList', (_message.Message,), dict(
  DESCRIPTOR = _NETWORKLIST,
  __module__ = 'ipfs_pb2'
  # @@protoc_insertion_point(class_scope:ipfs.NetworkList)
  ))
_sym_db.RegisterMessage(NetworkList)

NetworkDetails = _reflection.GeneratedProtocolMessageType('NetworkDetails', (_message.Message,), dict(
  DESCRIPTOR = _NETWORKDETAILS,
  __module__ = 'ipfs_pb2'
  # @@protoc_insertion_point(class_scope:ipfs.NetworkDetails)
  ))
_sym_db.RegisterMessage(NetworkDetails)


DESCRIPTOR._options = None

_TEMPORALIPFS = _descriptor.ServiceDescriptor(
  name='TemporalIPFS',
  full_name='ipfs.TemporalIPFS',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=397,
  serialized_end=901,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateNetwork',
    full_name='ipfs.TemporalIPFS.CreateNetwork',
    index=0,
    containing_service=None,
    input_type=_CREATENETWORKREQ,
    output_type=_NETWORKDETAILS,
    serialized_options=_b('\202\323\344\223\002\032\"\030/v3/ipfs/networks/create'),
  ),
  _descriptor.MethodDescriptor(
    name='StartNetwork',
    full_name='ipfs.TemporalIPFS.StartNetwork',
    index=1,
    containing_service=None,
    input_type=_NETWORK,
    output_type=_EMPTY,
    serialized_options=_b('\202\323\344\223\002\031\"\027/v3/ipfs/networks/start'),
  ),
  _descriptor.MethodDescriptor(
    name='StopNetwork',
    full_name='ipfs.TemporalIPFS.StopNetwork',
    index=2,
    containing_service=None,
    input_type=_NETWORK,
    output_type=_EMPTY,
    serialized_options=_b('\202\323\344\223\002\030\"\026/v3/ipfs/networks/stop'),
  ),
  _descriptor.MethodDescriptor(
    name='RemoveNetwork',
    full_name='ipfs.TemporalIPFS.RemoveNetwork',
    index=3,
    containing_service=None,
    input_type=_NETWORK,
    output_type=_EMPTY,
    serialized_options=_b('\202\323\344\223\002\030\"\026/v3/ipfs/networks/stop'),
  ),
  _descriptor.MethodDescriptor(
    name='NetworkInfo',
    full_name='ipfs.TemporalIPFS.NetworkInfo',
    index=4,
    containing_service=None,
    input_type=_NETWORK,
    output_type=_NETWORKDETAILS,
    serialized_options=_b('\202\323\344\223\002\030\022\026/v3/ipfs/networks/stat'),
  ),
  _descriptor.MethodDescriptor(
    name='ListNetworks',
    full_name='ipfs.TemporalIPFS.ListNetworks',
    index=5,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_NETWORKLIST,
    serialized_options=_b('\202\323\344\223\002\030\"\026/v3/ipfs/networks/list'),
  ),
])
_sym_db.RegisterServiceDescriptor(_TEMPORALIPFS)

DESCRIPTOR.services_by_name['TemporalIPFS'] = _TEMPORALIPFS

# @@protoc_insertion_point(module_scope)
