# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ipfs_pb2 as ipfs__pb2


class TemporalIPFSStub(object):
  """TemporalIPFS implements Temporal's IPFS management APIs, most notably private
  networks.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateNetwork = channel.unary_unary(
        '/ipfs.TemporalIPFS/CreateNetwork',
        request_serializer=ipfs__pb2.CreateNetworkReq.SerializeToString,
        response_deserializer=ipfs__pb2.NetworkDetails.FromString,
        )
    self.StartNetwork = channel.unary_unary(
        '/ipfs.TemporalIPFS/StartNetwork',
        request_serializer=ipfs__pb2.Network.SerializeToString,
        response_deserializer=ipfs__pb2.Empty.FromString,
        )
    self.StopNetwork = channel.unary_unary(
        '/ipfs.TemporalIPFS/StopNetwork',
        request_serializer=ipfs__pb2.Network.SerializeToString,
        response_deserializer=ipfs__pb2.Empty.FromString,
        )
    self.RemoveNetwork = channel.unary_unary(
        '/ipfs.TemporalIPFS/RemoveNetwork',
        request_serializer=ipfs__pb2.Network.SerializeToString,
        response_deserializer=ipfs__pb2.Empty.FromString,
        )
    self.NetworkInfo = channel.unary_unary(
        '/ipfs.TemporalIPFS/NetworkInfo',
        request_serializer=ipfs__pb2.Network.SerializeToString,
        response_deserializer=ipfs__pb2.NetworkDetails.FromString,
        )
    self.ListNetworks = channel.unary_unary(
        '/ipfs.TemporalIPFS/ListNetworks',
        request_serializer=ipfs__pb2.Empty.SerializeToString,
        response_deserializer=ipfs__pb2.NetworkList.FromString,
        )


class TemporalIPFSServicer(object):
  """TemporalIPFS implements Temporal's IPFS management APIs, most notably private
  networks.
  """

  def CreateNetwork(self, request, context):
    """CreateNetwork creates a new hosted IPFS network
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StartNetwork(self, request, context):
    """StartNetwork spins up a previously created IPFS network
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StopNetwork(self, request, context):
    """StopNetwork shuts down an IPFS network
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveNetwork(self, request, context):
    """RemoveNetwork deletes an IPFS network
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NetworkInfo(self, request, context):
    """NetworkInfo retrieves information about a network
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListNetworks(self, request, context):
    """ListNetworks retrieves a list of the authenticated user's networks
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TemporalIPFSServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateNetwork': grpc.unary_unary_rpc_method_handler(
          servicer.CreateNetwork,
          request_deserializer=ipfs__pb2.CreateNetworkReq.FromString,
          response_serializer=ipfs__pb2.NetworkDetails.SerializeToString,
      ),
      'StartNetwork': grpc.unary_unary_rpc_method_handler(
          servicer.StartNetwork,
          request_deserializer=ipfs__pb2.Network.FromString,
          response_serializer=ipfs__pb2.Empty.SerializeToString,
      ),
      'StopNetwork': grpc.unary_unary_rpc_method_handler(
          servicer.StopNetwork,
          request_deserializer=ipfs__pb2.Network.FromString,
          response_serializer=ipfs__pb2.Empty.SerializeToString,
      ),
      'RemoveNetwork': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveNetwork,
          request_deserializer=ipfs__pb2.Network.FromString,
          response_serializer=ipfs__pb2.Empty.SerializeToString,
      ),
      'NetworkInfo': grpc.unary_unary_rpc_method_handler(
          servicer.NetworkInfo,
          request_deserializer=ipfs__pb2.Network.FromString,
          response_serializer=ipfs__pb2.NetworkDetails.SerializeToString,
      ),
      'ListNetworks': grpc.unary_unary_rpc_method_handler(
          servicer.ListNetworks,
          request_deserializer=ipfs__pb2.Empty.FromString,
          response_serializer=ipfs__pb2.NetworkList.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ipfs.TemporalIPFS', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
