# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import store_pb2 as store__pb2


class TemporalStoreStub(object):
  """TemporalStore implements Temporal's storage APIs
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Upload = channel.stream_unary(
        '/store.TemporalStore/Upload',
        request_serializer=store__pb2.UploadReq.SerializeToString,
        response_deserializer=store__pb2.Object.FromString,
        )
    self.Download = channel.unary_stream(
        '/store.TemporalStore/Download',
        request_serializer=store__pb2.DownloadReq.SerializeToString,
        response_deserializer=store__pb2.Blob.FromString,
        )
    self.Pin = channel.unary_unary(
        '/store.TemporalStore/Pin',
        request_serializer=store__pb2.Object.SerializeToString,
        response_deserializer=store__pb2.Empty.FromString,
        )
    self.Stat = channel.unary_unary(
        '/store.TemporalStore/Stat',
        request_serializer=store__pb2.Object.SerializeToString,
        response_deserializer=store__pb2.ObjectStats.FromString,
        )
    self.ListObjects = channel.unary_unary(
        '/store.TemporalStore/ListObjects',
        request_serializer=store__pb2.ListObjectsReq.SerializeToString,
        response_deserializer=store__pb2.ObjectList.FromString,
        )
    self.Publish = channel.unary_unary(
        '/store.TemporalStore/Publish',
        request_serializer=store__pb2.Event.SerializeToString,
        response_deserializer=store__pb2.Empty.FromString,
        )
    self.Subscribe = channel.unary_stream(
        '/store.TemporalStore/Subscribe',
        request_serializer=store__pb2.Topic.SerializeToString,
        response_deserializer=store__pb2.Event.FromString,
        )
    self.Keys = channel.unary_unary(
        '/store.TemporalStore/Keys',
        request_serializer=store__pb2.Empty.SerializeToString,
        response_deserializer=store__pb2.KeyList.FromString,
        )
    self.NewKey = channel.unary_unary(
        '/store.TemporalStore/NewKey',
        request_serializer=store__pb2.Key.SerializeToString,
        response_deserializer=store__pb2.Empty.FromString,
        )


class TemporalStoreServicer(object):
  """TemporalStore implements Temporal's storage APIs
  """

  def Upload(self, request_iterator, context):
    """OBJECT APIs 

    Upload accepts files and directories
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Download(self, request, context):
    """Download retrieves an object
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Pin(self, request, context):
    """Pin handles new pins and pin extensions
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Stat(self, request, context):
    """Stat retrieves details about an object
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListObjects(self, request, context):
    """ListObjects retrieves a list of the authenticated user's objects
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Publish(self, request, context):
    """IPFS PUBSUB 

    Publish publishes a message to the requested topic
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Subscribe(self, request, context):
    """Subscribe subscribes to messages from the requested topic
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Keys(self, request, context):
    """IPFS KEYS 

    Keys returns the IPFS keys associated with an authenticated request
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NewKey(self, request, context):
    """NewKey generates a new IPFS key associated with an authenticated request.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TemporalStoreServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Upload': grpc.stream_unary_rpc_method_handler(
          servicer.Upload,
          request_deserializer=store__pb2.UploadReq.FromString,
          response_serializer=store__pb2.Object.SerializeToString,
      ),
      'Download': grpc.unary_stream_rpc_method_handler(
          servicer.Download,
          request_deserializer=store__pb2.DownloadReq.FromString,
          response_serializer=store__pb2.Blob.SerializeToString,
      ),
      'Pin': grpc.unary_unary_rpc_method_handler(
          servicer.Pin,
          request_deserializer=store__pb2.Object.FromString,
          response_serializer=store__pb2.Empty.SerializeToString,
      ),
      'Stat': grpc.unary_unary_rpc_method_handler(
          servicer.Stat,
          request_deserializer=store__pb2.Object.FromString,
          response_serializer=store__pb2.ObjectStats.SerializeToString,
      ),
      'ListObjects': grpc.unary_unary_rpc_method_handler(
          servicer.ListObjects,
          request_deserializer=store__pb2.ListObjectsReq.FromString,
          response_serializer=store__pb2.ObjectList.SerializeToString,
      ),
      'Publish': grpc.unary_unary_rpc_method_handler(
          servicer.Publish,
          request_deserializer=store__pb2.Event.FromString,
          response_serializer=store__pb2.Empty.SerializeToString,
      ),
      'Subscribe': grpc.unary_stream_rpc_method_handler(
          servicer.Subscribe,
          request_deserializer=store__pb2.Topic.FromString,
          response_serializer=store__pb2.Event.SerializeToString,
      ),
      'Keys': grpc.unary_unary_rpc_method_handler(
          servicer.Keys,
          request_deserializer=store__pb2.Empty.FromString,
          response_serializer=store__pb2.KeyList.SerializeToString,
      ),
      'NewKey': grpc.unary_unary_rpc_method_handler(
          servicer.NewKey,
          request_deserializer=store__pb2.Key.FromString,
          response_serializer=store__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'store.TemporalStore', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
