// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/store.proto

package store // import "github.com/RTradeLtd/sdk/go/temporal/store"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_store_61ed32709236ea4d, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "store.Message")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TemporalStoreClient is the client API for TemporalStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TemporalStoreClient interface {
	Status(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
}

type temporalStoreClient struct {
	cc *grpc.ClientConn
}

func NewTemporalStoreClient(cc *grpc.ClientConn) TemporalStoreClient {
	return &temporalStoreClient{cc}
}

func (c *temporalStoreClient) Status(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/store.TemporalStore/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemporalStoreServer is the server API for TemporalStore service.
func init() { proto.RegisterFile("proto/store.proto", fileDescriptor_store_61ed32709236ea4d) }

var fileDescriptor_store_61ed32709236ea4d = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x2e, 0xc9, 0x2f, 0x4a, 0xd5, 0x03, 0xb3, 0x85, 0x58, 0xc1, 0x1c, 0x29, 0x99,
	0xf4, 0xfc, 0xfc, 0xf4, 0x9c, 0x54, 0xfd, 0xc4, 0x82, 0x4c, 0xfd, 0xc4, 0xbc, 0xbc, 0xfc, 0x92,
	0xc4, 0x92, 0xcc, 0xfc, 0xbc, 0x62, 0x88, 0x22, 0x25, 0x65, 0x2e, 0x76, 0xdf, 0xd4, 0xe2, 0xe2,
	0xc4, 0xf4, 0x54, 0x21, 0x09, 0x2e, 0xf6, 0x5c, 0x08, 0x53, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33,
	0x08, 0xc6, 0x35, 0x0a, 0xe6, 0xe2, 0x0d, 0x49, 0xcd, 0x2d, 0xc8, 0x2f, 0x4a, 0xcc, 0x09, 0x06,
	0x99, 0x29, 0xe4, 0xc4, 0xc5, 0x16, 0x5c, 0x92, 0x58, 0x52, 0x5a, 0x2c, 0xc4, 0xa7, 0x07, 0xb1,
	0x12, 0x6a, 0x88, 0x14, 0x1a, 0x5f, 0x49, 0xa2, 0xe9, 0xf2, 0x93, 0xc9, 0x4c, 0x42, 0x42, 0x02,
	0xfa, 0x65, 0xc6, 0x10, 0xd7, 0xe9, 0x17, 0x83, 0x75, 0x3a, 0x39, 0x71, 0x89, 0x24, 0xe7, 0xe4,
	0x97, 0xa6, 0xe8, 0x95, 0x40, 0x8d, 0x86, 0xe8, 0x8c, 0xd2, 0x4a, 0xcf, 0x2c, 0xc9, 0x28, 0x4d,
	0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x0f, 0x0a, 0x29, 0x4a, 0x4c, 0x49, 0xf5, 0x29, 0x49, 0xd1, 0x2f,
	0x4e, 0xc9, 0xd6, 0x4f, 0xcf, 0xd7, 0x87, 0xa9, 0x85, 0x18, 0x95, 0xc4, 0x06, 0xf6, 0x84, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0x88, 0x98, 0x77, 0x42, 0xfe, 0x00, 0x00, 0x00,
}
