// Code generated by protoc-gen-go. DO NOT EDIT.
// source: store.proto

package store

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Key_RSA_Size int32

const (
	Key_RSA_S_2048 Key_RSA_Size = 0
	Key_RSA_S_3072 Key_RSA_Size = 1
	Key_RSA_S_4096 Key_RSA_Size = 2
)

var Key_RSA_Size_name = map[int32]string{
	0: "S_2048",
	1: "S_3072",
	2: "S_4096",
}

var Key_RSA_Size_value = map[string]int32{
	"S_2048": 0,
	"S_3072": 1,
	"S_4096": 2,
}

func (x Key_RSA_Size) String() string {
	return proto.EnumName(Key_RSA_Size_name, int32(x))
}

func (Key_RSA_Size) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{8, 0, 0}
}

type Key_ED25519_Size int32

const (
	Key_ED25519_S_256 Key_ED25519_Size = 0
)

var Key_ED25519_Size_name = map[int32]string{
	0: "S_256",
}

var Key_ED25519_Size_value = map[string]int32{
	"S_256": 0,
}

func (x Key_ED25519_Size) String() string {
	return proto.EnumName(Key_ED25519_Size_name, int32(x))
}

func (Key_ED25519_Size) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{8, 1, 0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Message struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ObjectStats struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	BlockSize            int32    `protobuf:"varint,2,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	CumulativeSize       int32    `protobuf:"varint,3,opt,name=cumulative_size,json=cumulativeSize,proto3" json:"cumulative_size,omitempty"`
	DataSize             int32    `protobuf:"varint,4,opt,name=data_size,json=dataSize,proto3" json:"data_size,omitempty"`
	LinksSize            int32    `protobuf:"varint,5,opt,name=links_size,json=linksSize,proto3" json:"links_size,omitempty"`
	LinkCount            int32    `protobuf:"varint,6,opt,name=link_count,json=linkCount,proto3" json:"link_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectStats) Reset()         { *m = ObjectStats{} }
func (m *ObjectStats) String() string { return proto.CompactTextString(m) }
func (*ObjectStats) ProtoMessage()    {}
func (*ObjectStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{2}
}

func (m *ObjectStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectStats.Unmarshal(m, b)
}
func (m *ObjectStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectStats.Marshal(b, m, deterministic)
}
func (m *ObjectStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectStats.Merge(m, src)
}
func (m *ObjectStats) XXX_Size() int {
	return xxx_messageInfo_ObjectStats.Size(m)
}
func (m *ObjectStats) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectStats.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectStats proto.InternalMessageInfo

func (m *ObjectStats) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *ObjectStats) GetBlockSize() int32 {
	if m != nil {
		return m.BlockSize
	}
	return 0
}

func (m *ObjectStats) GetCumulativeSize() int32 {
	if m != nil {
		return m.CumulativeSize
	}
	return 0
}

func (m *ObjectStats) GetDataSize() int32 {
	if m != nil {
		return m.DataSize
	}
	return 0
}

func (m *ObjectStats) GetLinksSize() int32 {
	if m != nil {
		return m.LinksSize
	}
	return 0
}

func (m *ObjectStats) GetLinkCount() int32 {
	if m != nil {
		return m.LinkCount
	}
	return 0
}

type KeysResp struct {
	Keys                 []*Key   `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeysResp) Reset()         { *m = KeysResp{} }
func (m *KeysResp) String() string { return proto.CompactTextString(m) }
func (*KeysResp) ProtoMessage()    {}
func (*KeysResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{3}
}

func (m *KeysResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeysResp.Unmarshal(m, b)
}
func (m *KeysResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeysResp.Marshal(b, m, deterministic)
}
func (m *KeysResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeysResp.Merge(m, src)
}
func (m *KeysResp) XXX_Size() int {
	return xxx_messageInfo_KeysResp.Size(m)
}
func (m *KeysResp) XXX_DiscardUnknown() {
	xxx_messageInfo_KeysResp.DiscardUnknown(m)
}

var xxx_messageInfo_KeysResp proto.InternalMessageInfo

func (m *KeysResp) GetKeys() []*Key {
	if m != nil {
		return m.Keys
	}
	return nil
}

type Object struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{4}
}

func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (m *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(m, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type Blob struct {
	Content              []byte        `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	HoldTime             int64         `protobuf:"varint,2,opt,name=hold_time,json=holdTime,proto3" json:"hold_time,omitempty"`
	Options              *Blob_Options `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Blob) Reset()         { *m = Blob{} }
func (m *Blob) String() string { return proto.CompactTextString(m) }
func (*Blob) ProtoMessage()    {}
func (*Blob) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{5}
}

func (m *Blob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blob.Unmarshal(m, b)
}
func (m *Blob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blob.Marshal(b, m, deterministic)
}
func (m *Blob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blob.Merge(m, src)
}
func (m *Blob) XXX_Size() int {
	return xxx_messageInfo_Blob.Size(m)
}
func (m *Blob) XXX_DiscardUnknown() {
	xxx_messageInfo_Blob.DiscardUnknown(m)
}

var xxx_messageInfo_Blob proto.InternalMessageInfo

func (m *Blob) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Blob) GetHoldTime() int64 {
	if m != nil {
		return m.HoldTime
	}
	return 0
}

func (m *Blob) GetOptions() *Blob_Options {
	if m != nil {
		return m.Options
	}
	return nil
}

type Blob_Options struct {
	Passphrase           string   `protobuf:"bytes,1,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blob_Options) Reset()         { *m = Blob_Options{} }
func (m *Blob_Options) String() string { return proto.CompactTextString(m) }
func (*Blob_Options) ProtoMessage()    {}
func (*Blob_Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{5, 0}
}

func (m *Blob_Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blob_Options.Unmarshal(m, b)
}
func (m *Blob_Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blob_Options.Marshal(b, m, deterministic)
}
func (m *Blob_Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blob_Options.Merge(m, src)
}
func (m *Blob_Options) XXX_Size() int {
	return xxx_messageInfo_Blob_Options.Size(m)
}
func (m *Blob_Options) XXX_DiscardUnknown() {
	xxx_messageInfo_Blob_Options.DiscardUnknown(m)
}

var xxx_messageInfo_Blob_Options proto.InternalMessageInfo

func (m *Blob_Options) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

type Event struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{6}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Event) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Topic struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Topic) Reset()         { *m = Topic{} }
func (m *Topic) String() string { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()    {}
func (*Topic) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{7}
}

func (m *Topic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic.Unmarshal(m, b)
}
func (m *Topic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic.Marshal(b, m, deterministic)
}
func (m *Topic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic.Merge(m, src)
}
func (m *Topic) XXX_Size() int {
	return xxx_messageInfo_Topic.Size(m)
}
func (m *Topic) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic.DiscardUnknown(m)
}

var xxx_messageInfo_Topic proto.InternalMessageInfo

func (m *Topic) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type Key struct {
	// Types that are valid to be assigned to Type:
	//	*Key_Rsa
	//	*Key_Ed25519
	Type                 isKey_Type `protobuf_oneof:"type"`
	Name                 string     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string     `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{8}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

type isKey_Type interface {
	isKey_Type()
}

type Key_Rsa struct {
	Rsa *Key_RSA `protobuf:"bytes,1,opt,name=rsa,proto3,oneof"`
}

type Key_Ed25519 struct {
	Ed25519 *Key_ED25519 `protobuf:"bytes,2,opt,name=ed25519,proto3,oneof"`
}

func (*Key_Rsa) isKey_Type() {}

func (*Key_Ed25519) isKey_Type() {}

func (m *Key) GetType() isKey_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Key) GetRsa() *Key_RSA {
	if x, ok := m.GetType().(*Key_Rsa); ok {
		return x.Rsa
	}
	return nil
}

func (m *Key) GetEd25519() *Key_ED25519 {
	if x, ok := m.GetType().(*Key_Ed25519); ok {
		return x.Ed25519
	}
	return nil
}

func (m *Key) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Key) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Key) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Key_Rsa)(nil),
		(*Key_Ed25519)(nil),
	}
}

type Key_RSA struct {
	Size                 Key_RSA_Size `protobuf:"varint,1,opt,name=size,proto3,enum=store.Key_RSA_Size" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Key_RSA) Reset()         { *m = Key_RSA{} }
func (m *Key_RSA) String() string { return proto.CompactTextString(m) }
func (*Key_RSA) ProtoMessage()    {}
func (*Key_RSA) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{8, 0}
}

func (m *Key_RSA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key_RSA.Unmarshal(m, b)
}
func (m *Key_RSA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key_RSA.Marshal(b, m, deterministic)
}
func (m *Key_RSA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key_RSA.Merge(m, src)
}
func (m *Key_RSA) XXX_Size() int {
	return xxx_messageInfo_Key_RSA.Size(m)
}
func (m *Key_RSA) XXX_DiscardUnknown() {
	xxx_messageInfo_Key_RSA.DiscardUnknown(m)
}

var xxx_messageInfo_Key_RSA proto.InternalMessageInfo

func (m *Key_RSA) GetSize() Key_RSA_Size {
	if m != nil {
		return m.Size
	}
	return Key_RSA_S_2048
}

type Key_ED25519 struct {
	Size                 Key_ED25519_Size `protobuf:"varint,1,opt,name=size,proto3,enum=store.Key_ED25519_Size" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Key_ED25519) Reset()         { *m = Key_ED25519{} }
func (m *Key_ED25519) String() string { return proto.CompactTextString(m) }
func (*Key_ED25519) ProtoMessage()    {}
func (*Key_ED25519) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{8, 1}
}

func (m *Key_ED25519) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key_ED25519.Unmarshal(m, b)
}
func (m *Key_ED25519) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key_ED25519.Marshal(b, m, deterministic)
}
func (m *Key_ED25519) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key_ED25519.Merge(m, src)
}
func (m *Key_ED25519) XXX_Size() int {
	return xxx_messageInfo_Key_ED25519.Size(m)
}
func (m *Key_ED25519) XXX_DiscardUnknown() {
	xxx_messageInfo_Key_ED25519.DiscardUnknown(m)
}

var xxx_messageInfo_Key_ED25519 proto.InternalMessageInfo

func (m *Key_ED25519) GetSize() Key_ED25519_Size {
	if m != nil {
		return m.Size
	}
	return Key_ED25519_S_256
}

func init() {
	proto.RegisterEnum("store.Key_RSA_Size", Key_RSA_Size_name, Key_RSA_Size_value)
	proto.RegisterEnum("store.Key_ED25519_Size", Key_ED25519_Size_name, Key_ED25519_Size_value)
	proto.RegisterType((*Empty)(nil), "store.Empty")
	proto.RegisterType((*Message)(nil), "store.Message")
	proto.RegisterType((*ObjectStats)(nil), "store.ObjectStats")
	proto.RegisterType((*KeysResp)(nil), "store.KeysResp")
	proto.RegisterType((*Object)(nil), "store.Object")
	proto.RegisterType((*Blob)(nil), "store.Blob")
	proto.RegisterType((*Blob_Options)(nil), "store.Blob.Options")
	proto.RegisterType((*Event)(nil), "store.Event")
	proto.RegisterType((*Topic)(nil), "store.Topic")
	proto.RegisterType((*Key)(nil), "store.Key")
	proto.RegisterType((*Key_RSA)(nil), "store.Key.RSA")
	proto.RegisterType((*Key_ED25519)(nil), "store.Key.ED25519")
}

func init() { proto.RegisterFile("store.proto", fileDescriptor_98bbca36ef968dfc) }

var fileDescriptor_98bbca36ef968dfc = []byte{
	// 788 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0xdd, 0x72, 0xdb, 0x44,
	0x14, 0x8e, 0x6c, 0x59, 0x8a, 0x8f, 0x1b, 0xc7, 0xdd, 0x96, 0xd6, 0x51, 0x9b, 0x12, 0x96, 0x8b,
	0x86, 0x32, 0xd8, 0x41, 0x69, 0x5a, 0x3a, 0xc0, 0x0c, 0x09, 0x84, 0x29, 0x13, 0xa0, 0x1d, 0x29,
	0xdc, 0x70, 0xe3, 0x91, 0xe4, 0x25, 0x5e, 0x22, 0x6b, 0x35, 0xde, 0x55, 0x3a, 0xee, 0x25, 0xaf,
	0xc0, 0x05, 0xaf, 0xc0, 0x05, 0x8f, 0xc1, 0x1b, 0xf0, 0x0a, 0x3c, 0x48, 0x67, 0xcf, 0x4a, 0xb1,
	0xe4, 0xe6, 0x4a, 0x7b, 0xce, 0xf9, 0xbe, 0xef, 0xec, 0x9e, 0x1f, 0x41, 0x4f, 0x2a, 0xb1, 0x60,
	0xa3, 0x7c, 0x21, 0x94, 0x20, 0x1d, 0x34, 0xbc, 0x87, 0x17, 0x42, 0x5c, 0xa4, 0x6c, 0x1c, 0xe5,
	0x7c, 0x1c, 0x65, 0x99, 0x50, 0x91, 0xe2, 0x22, 0x93, 0x06, 0x44, 0x5d, 0xe8, 0x9c, 0xce, 0x73,
	0xb5, 0xa4, 0x1f, 0x83, 0xfb, 0x13, 0x93, 0x32, 0xba, 0x60, 0x64, 0x08, 0xee, 0xdc, 0x1c, 0x87,
	0xd6, 0x9e, 0xb5, 0xdf, 0x0d, 0x2a, 0x93, 0xfe, 0x6b, 0x41, 0xef, 0x55, 0xfc, 0x3b, 0x4b, 0x54,
	0xa8, 0x22, 0x25, 0x09, 0x01, 0x7b, 0x16, 0xc9, 0x59, 0x09, 0xc3, 0x33, 0xd9, 0x05, 0x88, 0x53,
	0x91, 0x5c, 0x4e, 0x24, 0x7f, 0xcb, 0x86, 0xad, 0x3d, 0x6b, 0xbf, 0x13, 0x74, 0xd1, 0x13, 0xf2,
	0xb7, 0x8c, 0x3c, 0x86, 0xed, 0xa4, 0x98, 0x17, 0x69, 0xa4, 0xf8, 0x15, 0x33, 0x98, 0x36, 0x62,
	0xfa, 0x2b, 0x37, 0x02, 0x1f, 0x40, 0x77, 0x1a, 0xa9, 0xc8, 0x40, 0x6c, 0x84, 0x6c, 0x6a, 0x07,
	0x06, 0x77, 0x01, 0x52, 0x9e, 0x5d, 0x4a, 0x13, 0xed, 0x98, 0x24, 0xe8, 0xa9, 0x87, 0x27, 0x89,
	0x28, 0x32, 0x35, 0x74, 0x56, 0xe1, 0x6f, 0xb5, 0x83, 0x3e, 0x81, 0xcd, 0x33, 0xb6, 0x94, 0x01,
	0x93, 0x39, 0x79, 0x04, 0xf6, 0x25, 0x5b, 0xca, 0xa1, 0xb5, 0xd7, 0xde, 0xef, 0xf9, 0x30, 0x32,
	0x15, 0x3c, 0x63, 0xcb, 0x00, 0xfd, 0xf4, 0x21, 0x38, 0xe6, 0xc5, 0x37, 0x3d, 0x96, 0xfe, 0x65,
	0x81, 0x7d, 0x92, 0x8a, 0x58, 0xd7, 0x2c, 0x11, 0x99, 0x62, 0x99, 0xc2, 0xf8, 0xad, 0xa0, 0x32,
	0xf5, 0x3b, 0x66, 0x22, 0x9d, 0x4e, 0x14, 0x9f, 0x9b, 0x72, 0xb4, 0x83, 0x4d, 0xed, 0x38, 0xe7,
	0x73, 0x46, 0x3e, 0x03, 0x57, 0xe4, 0xd8, 0x0f, 0xac, 0x42, 0xcf, 0xbf, 0x53, 0x5e, 0x40, 0x8b,
	0x8e, 0x5e, 0x99, 0x50, 0x50, 0x61, 0xbc, 0x4f, 0xc0, 0x2d, 0x7d, 0xe4, 0x11, 0x40, 0x1e, 0x49,
	0x99, 0xcf, 0x16, 0x91, 0xac, 0xfa, 0x54, 0xf3, 0xd0, 0xe7, 0xd0, 0x39, 0xbd, 0xd2, 0xf9, 0xef,
	0x42, 0x47, 0x89, 0x9c, 0x27, 0x25, 0xc6, 0x18, 0xf5, 0x1e, 0xb7, 0x9a, 0x3d, 0xde, 0x85, 0xce,
	0x39, 0x42, 0x6e, 0x24, 0xd2, 0x7f, 0x5a, 0xd0, 0x3e, 0x63, 0x4b, 0x42, 0xa1, 0xbd, 0x90, 0x11,
	0xc6, 0x7a, 0x7e, 0x7f, 0x55, 0xb6, 0x51, 0x10, 0x1e, 0xbf, 0xdc, 0x08, 0x74, 0x90, 0x8c, 0xc0,
	0x65, 0x53, 0xff, 0xe8, 0xe8, 0xf3, 0x17, 0x98, 0xa4, 0xe7, 0x93, 0x1a, 0xee, 0xf4, 0x3b, 0x8c,
	0xbc, 0xdc, 0x08, 0x2a, 0x90, 0xae, 0x70, 0x16, 0xcd, 0xcd, 0x40, 0x74, 0x03, 0x3c, 0x93, 0x3e,
	0xb4, 0xf8, 0x14, 0xfb, 0xdf, 0x0d, 0x5a, 0x7c, 0xea, 0xfd, 0x0a, 0xed, 0x20, 0x3c, 0x26, 0x8f,
	0xc1, 0xc6, 0xd6, 0xeb, 0xfc, 0xfd, 0xeb, 0xaa, 0x95, 0xf9, 0x47, 0x7a, 0x08, 0x02, 0x04, 0xd0,
	0x27, 0x60, 0xe3, 0x48, 0x00, 0x38, 0xe1, 0xc4, 0x3f, 0x78, 0xfa, 0xc5, 0x60, 0xc3, 0x9c, 0x0f,
	0x0f, 0x9e, 0xfb, 0x03, 0xcb, 0x9c, 0x9f, 0x1e, 0xbc, 0x78, 0x36, 0x68, 0x79, 0x3f, 0x80, 0x5b,
	0xde, 0x8a, 0x7c, 0xda, 0xd0, 0xbf, 0xff, 0xfe, 0xbd, 0xeb, 0x39, 0x6e, 0x97, 0x39, 0xba, 0xd0,
	0x09, 0x27, 0xfe, 0xd1, 0xb3, 0xc1, 0xc6, 0x89, 0x03, 0xb6, 0x5a, 0xe6, 0xcc, 0xff, 0xdb, 0x86,
	0xad, 0x73, 0x36, 0xcf, 0xc5, 0x22, 0x4a, 0x43, 0xad, 0x41, 0x4e, 0xc0, 0xd1, 0xcb, 0x53, 0x48,
	0x52, 0x55, 0xad, 0xdc, 0x3b, 0x6f, 0xcd, 0xa6, 0xc3, 0x3f, 0xfe, 0xfb, 0xff, 0xcf, 0x16, 0x21,
	0x83, 0xf1, 0xd5, 0xe1, 0x18, 0x43, 0x63, 0x69, 0x98, 0xdf, 0x80, 0xf3, 0x4b, 0x9e, 0x8a, 0x68,
	0x4a, 0x7a, 0xb5, 0x79, 0xf1, 0xb6, 0x4a, 0xc3, 0x0c, 0x6c, 0xc5, 0xa7, 0x35, 0x7e, 0x81, 0xac,
	0x7d, 0x8b, 0x7c, 0x09, 0xed, 0xd7, 0x3c, 0x23, 0x4d, 0xc6, 0x7b, 0x37, 0xf8, 0x00, 0x15, 0xb6,
	0xc9, 0xd6, 0x4a, 0x21, 0xe7, 0x19, 0x39, 0x06, 0x5b, 0x3f, 0x61, 0x9d, 0x4d, 0x1a, 0x26, 0xfe,
	0x21, 0xe8, 0x3d, 0x54, 0x18, 0x90, 0x7e, 0xf3, 0x0d, 0xe4, 0x2b, 0xb0, 0xf5, 0x0a, 0x92, 0x5b,
	0x25, 0x07, 0x7f, 0x42, 0xde, 0xf6, 0xaa, 0xce, 0xb8, 0x9d, 0xcd, 0x0b, 0xf0, 0xfc, 0x37, 0x39,
	0xd6, 0x4b, 0x49, 0xbe, 0x06, 0xe7, 0x67, 0xf6, 0x46, 0x8f, 0x61, 0x6d, 0x61, 0xbd, 0x86, 0x16,
	0xdd, 0x41, 0xea, 0x1d, 0x7a, 0xbb, 0x41, 0x1d, 0x67, 0xec, 0x0d, 0xf9, 0x1e, 0xdc, 0xd7, 0x45,
	0x9c, 0x72, 0x39, 0x5b, 0xe5, 0xd7, 0xbb, 0xb2, 0xa6, 0xf0, 0x21, 0x2a, 0xec, 0xd0, 0xfb, 0xd7,
	0x0a, 0x79, 0x11, 0xcb, 0x22, 0xd6, 0x1f, 0x24, 0xff, 0x08, 0xdd, 0xb0, 0x88, 0x65, 0xb2, 0xe0,
	0x31, 0xbb, 0x56, 0xc2, 0xe5, 0xf1, 0x1a, 0xba, 0xf4, 0x23, 0x54, 0x7a, 0x40, 0x76, 0xd6, 0x95,
	0x64, 0x45, 0x3f, 0xb0, 0x4e, 0xee, 0xc1, 0xdd, 0x24, 0x15, 0xc5, 0x74, 0xa4, 0xca, 0x79, 0x31,
	0x12, 0xb1, 0x83, 0x7f, 0xea, 0xc3, 0x77, 0x01, 0x00, 0x00, 0xff, 0xff, 0x70, 0x4f, 0x39, 0x1d,
	0xdd, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TemporalStoreClient is the client API for TemporalStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TemporalStoreClient interface {
	Status(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	// Upload accepts files and directories
	Upload(ctx context.Context, opts ...grpc.CallOption) (TemporalStore_UploadClient, error)
	// Pin handles new pins and pin extensions
	Pin(ctx context.Context, in *Object, opts ...grpc.CallOption) (*Message, error)
	// Stat retrieves details about an object
	Stat(ctx context.Context, in *Object, opts ...grpc.CallOption) (*ObjectStats, error)
	// Keys returns the IPFS keys associated with an authenticated request.
	Keys(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*KeysResp, error)
	// NewKey generates a new IPFS key associated with an authenticated request.
	NewKey(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Empty, error)
	Publish(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Empty, error)
	Subscribe(ctx context.Context, in *Topic, opts ...grpc.CallOption) (TemporalStore_SubscribeClient, error)
}

type temporalStoreClient struct {
	cc *grpc.ClientConn
}

func NewTemporalStoreClient(cc *grpc.ClientConn) TemporalStoreClient {
	return &temporalStoreClient{cc}
}

func (c *temporalStoreClient) Status(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/store.TemporalStore/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temporalStoreClient) Upload(ctx context.Context, opts ...grpc.CallOption) (TemporalStore_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TemporalStore_serviceDesc.Streams[0], "/store.TemporalStore/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &temporalStoreUploadClient{stream}
	return x, nil
}

type TemporalStore_UploadClient interface {
	Send(*Blob) error
	CloseAndRecv() (*Object, error)
	grpc.ClientStream
}

type temporalStoreUploadClient struct {
	grpc.ClientStream
}

func (x *temporalStoreUploadClient) Send(m *Blob) error {
	return x.ClientStream.SendMsg(m)
}

func (x *temporalStoreUploadClient) CloseAndRecv() (*Object, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Object)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *temporalStoreClient) Pin(ctx context.Context, in *Object, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/store.TemporalStore/Pin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temporalStoreClient) Stat(ctx context.Context, in *Object, opts ...grpc.CallOption) (*ObjectStats, error) {
	out := new(ObjectStats)
	err := c.cc.Invoke(ctx, "/store.TemporalStore/Stat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temporalStoreClient) Keys(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*KeysResp, error) {
	out := new(KeysResp)
	err := c.cc.Invoke(ctx, "/store.TemporalStore/Keys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temporalStoreClient) NewKey(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/store.TemporalStore/NewKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temporalStoreClient) Publish(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/store.TemporalStore/Publish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temporalStoreClient) Subscribe(ctx context.Context, in *Topic, opts ...grpc.CallOption) (TemporalStore_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TemporalStore_serviceDesc.Streams[1], "/store.TemporalStore/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &temporalStoreSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TemporalStore_SubscribeClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type temporalStoreSubscribeClient struct {
	grpc.ClientStream
}

func (x *temporalStoreSubscribeClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TemporalStoreServer is the server API for TemporalStore service.
type TemporalStoreServer interface {
	Status(context.Context, *Message) (*Message, error)
	// Upload accepts files and directories
	Upload(TemporalStore_UploadServer) error
	// Pin handles new pins and pin extensions
	Pin(context.Context, *Object) (*Message, error)
	// Stat retrieves details about an object
	Stat(context.Context, *Object) (*ObjectStats, error)
	// Keys returns the IPFS keys associated with an authenticated request.
	Keys(context.Context, *Empty) (*KeysResp, error)
	// NewKey generates a new IPFS key associated with an authenticated request.
	NewKey(context.Context, *Key) (*Empty, error)
	Publish(context.Context, *Event) (*Empty, error)
	Subscribe(*Topic, TemporalStore_SubscribeServer) error
}

func RegisterTemporalStoreServer(s *grpc.Server, srv TemporalStoreServer) {
	s.RegisterService(&_TemporalStore_serviceDesc, srv)
}

func _TemporalStore_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalStoreServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.TemporalStore/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalStoreServer).Status(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemporalStore_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TemporalStoreServer).Upload(&temporalStoreUploadServer{stream})
}

type TemporalStore_UploadServer interface {
	SendAndClose(*Object) error
	Recv() (*Blob, error)
	grpc.ServerStream
}

type temporalStoreUploadServer struct {
	grpc.ServerStream
}

func (x *temporalStoreUploadServer) SendAndClose(m *Object) error {
	return x.ServerStream.SendMsg(m)
}

func (x *temporalStoreUploadServer) Recv() (*Blob, error) {
	m := new(Blob)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TemporalStore_Pin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Object)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalStoreServer).Pin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.TemporalStore/Pin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalStoreServer).Pin(ctx, req.(*Object))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemporalStore_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Object)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalStoreServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.TemporalStore/Stat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalStoreServer).Stat(ctx, req.(*Object))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemporalStore_Keys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalStoreServer).Keys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.TemporalStore/Keys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalStoreServer).Keys(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemporalStore_NewKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalStoreServer).NewKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.TemporalStore/NewKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalStoreServer).NewKey(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemporalStore_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalStoreServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.TemporalStore/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalStoreServer).Publish(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemporalStore_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Topic)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TemporalStoreServer).Subscribe(m, &temporalStoreSubscribeServer{stream})
}

type TemporalStore_SubscribeServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type temporalStoreSubscribeServer struct {
	grpc.ServerStream
}

func (x *temporalStoreSubscribeServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

var _TemporalStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "store.TemporalStore",
	HandlerType: (*TemporalStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _TemporalStore_Status_Handler,
		},
		{
			MethodName: "Pin",
			Handler:    _TemporalStore_Pin_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _TemporalStore_Stat_Handler,
		},
		{
			MethodName: "Keys",
			Handler:    _TemporalStore_Keys_Handler,
		},
		{
			MethodName: "NewKey",
			Handler:    _TemporalStore_NewKey_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _TemporalStore_Publish_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _TemporalStore_Upload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _TemporalStore_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "store.proto",
}
