/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_api_annotations_pb = require('./google/api/annotations_pb.js');
goog.exportSymbol('proto.ipfs.Empty', null, global);
goog.exportSymbol('proto.ipfs.Key', null, global);
goog.exportSymbol('proto.ipfs.Key.ED25519', null, global);
goog.exportSymbol('proto.ipfs.Key.ED25519.Size', null, global);
goog.exportSymbol('proto.ipfs.Key.RSA', null, global);
goog.exportSymbol('proto.ipfs.Key.RSA.Size', null, global);
goog.exportSymbol('proto.ipfs.KeysResp', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ipfs.Empty = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ipfs.Empty, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ipfs.Empty.displayName = 'proto.ipfs.Empty';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ipfs.Empty.prototype.toObject = function(opt_includeInstance) {
  return proto.ipfs.Empty.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ipfs.Empty} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ipfs.Empty.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ipfs.Empty}
 */
proto.ipfs.Empty.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ipfs.Empty;
  return proto.ipfs.Empty.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ipfs.Empty} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ipfs.Empty}
 */
proto.ipfs.Empty.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ipfs.Empty.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ipfs.Empty.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ipfs.Empty} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ipfs.Empty.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ipfs.KeysResp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ipfs.KeysResp.repeatedFields_, null);
};
goog.inherits(proto.ipfs.KeysResp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ipfs.KeysResp.displayName = 'proto.ipfs.KeysResp';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ipfs.KeysResp.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ipfs.KeysResp.prototype.toObject = function(opt_includeInstance) {
  return proto.ipfs.KeysResp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ipfs.KeysResp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ipfs.KeysResp.toObject = function(includeInstance, msg) {
  var f, obj = {
    keysList: jspb.Message.toObjectList(msg.getKeysList(),
    proto.ipfs.Key.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ipfs.KeysResp}
 */
proto.ipfs.KeysResp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ipfs.KeysResp;
  return proto.ipfs.KeysResp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ipfs.KeysResp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ipfs.KeysResp}
 */
proto.ipfs.KeysResp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.ipfs.Key;
      reader.readMessage(value,proto.ipfs.Key.deserializeBinaryFromReader);
      msg.addKeys(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ipfs.KeysResp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ipfs.KeysResp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ipfs.KeysResp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ipfs.KeysResp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKeysList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.ipfs.Key.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Key keys = 1;
 * @return {!Array<!proto.ipfs.Key>}
 */
proto.ipfs.KeysResp.prototype.getKeysList = function() {
  return /** @type{!Array<!proto.ipfs.Key>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ipfs.Key, 1));
};


/** @param {!Array<!proto.ipfs.Key>} value */
proto.ipfs.KeysResp.prototype.setKeysList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.ipfs.Key=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ipfs.Key}
 */
proto.ipfs.KeysResp.prototype.addKeys = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.ipfs.Key, opt_index);
};


proto.ipfs.KeysResp.prototype.clearKeysList = function() {
  this.setKeysList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ipfs.Key = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.ipfs.Key.oneofGroups_);
};
goog.inherits(proto.ipfs.Key, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ipfs.Key.displayName = 'proto.ipfs.Key';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.ipfs.Key.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.ipfs.Key.TypeCase = {
  TYPE_NOT_SET: 0,
  RSA: 1,
  ED25519: 2
};

/**
 * @return {proto.ipfs.Key.TypeCase}
 */
proto.ipfs.Key.prototype.getTypeCase = function() {
  return /** @type {proto.ipfs.Key.TypeCase} */(jspb.Message.computeOneofCase(this, proto.ipfs.Key.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ipfs.Key.prototype.toObject = function(opt_includeInstance) {
  return proto.ipfs.Key.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ipfs.Key} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ipfs.Key.toObject = function(includeInstance, msg) {
  var f, obj = {
    rsa: (f = msg.getRsa()) && proto.ipfs.Key.RSA.toObject(includeInstance, f),
    ed25519: (f = msg.getEd25519()) && proto.ipfs.Key.ED25519.toObject(includeInstance, f),
    name: jspb.Message.getFieldWithDefault(msg, 3, ""),
    id: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ipfs.Key}
 */
proto.ipfs.Key.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ipfs.Key;
  return proto.ipfs.Key.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ipfs.Key} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ipfs.Key}
 */
proto.ipfs.Key.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.ipfs.Key.RSA;
      reader.readMessage(value,proto.ipfs.Key.RSA.deserializeBinaryFromReader);
      msg.setRsa(value);
      break;
    case 2:
      var value = new proto.ipfs.Key.ED25519;
      reader.readMessage(value,proto.ipfs.Key.ED25519.deserializeBinaryFromReader);
      msg.setEd25519(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ipfs.Key.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ipfs.Key.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ipfs.Key} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ipfs.Key.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRsa();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.ipfs.Key.RSA.serializeBinaryToWriter
    );
  }
  f = message.getEd25519();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.ipfs.Key.ED25519.serializeBinaryToWriter
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ipfs.Key.RSA = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ipfs.Key.RSA, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ipfs.Key.RSA.displayName = 'proto.ipfs.Key.RSA';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ipfs.Key.RSA.prototype.toObject = function(opt_includeInstance) {
  return proto.ipfs.Key.RSA.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ipfs.Key.RSA} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ipfs.Key.RSA.toObject = function(includeInstance, msg) {
  var f, obj = {
    size: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ipfs.Key.RSA}
 */
proto.ipfs.Key.RSA.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ipfs.Key.RSA;
  return proto.ipfs.Key.RSA.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ipfs.Key.RSA} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ipfs.Key.RSA}
 */
proto.ipfs.Key.RSA.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.ipfs.Key.RSA.Size} */ (reader.readEnum());
      msg.setSize(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ipfs.Key.RSA.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ipfs.Key.RSA.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ipfs.Key.RSA} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ipfs.Key.RSA.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSize();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.ipfs.Key.RSA.Size = {
  S_2048: 0,
  S_3072: 1,
  S_4096: 2
};

/**
 * optional Size size = 1;
 * @return {!proto.ipfs.Key.RSA.Size}
 */
proto.ipfs.Key.RSA.prototype.getSize = function() {
  return /** @type {!proto.ipfs.Key.RSA.Size} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.ipfs.Key.RSA.Size} value */
proto.ipfs.Key.RSA.prototype.setSize = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ipfs.Key.ED25519 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ipfs.Key.ED25519, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ipfs.Key.ED25519.displayName = 'proto.ipfs.Key.ED25519';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ipfs.Key.ED25519.prototype.toObject = function(opt_includeInstance) {
  return proto.ipfs.Key.ED25519.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ipfs.Key.ED25519} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ipfs.Key.ED25519.toObject = function(includeInstance, msg) {
  var f, obj = {
    size: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ipfs.Key.ED25519}
 */
proto.ipfs.Key.ED25519.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ipfs.Key.ED25519;
  return proto.ipfs.Key.ED25519.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ipfs.Key.ED25519} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ipfs.Key.ED25519}
 */
proto.ipfs.Key.ED25519.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.ipfs.Key.ED25519.Size} */ (reader.readEnum());
      msg.setSize(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ipfs.Key.ED25519.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ipfs.Key.ED25519.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ipfs.Key.ED25519} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ipfs.Key.ED25519.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSize();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.ipfs.Key.ED25519.Size = {
  S_256: 0
};

/**
 * optional Size size = 1;
 * @return {!proto.ipfs.Key.ED25519.Size}
 */
proto.ipfs.Key.ED25519.prototype.getSize = function() {
  return /** @type {!proto.ipfs.Key.ED25519.Size} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.ipfs.Key.ED25519.Size} value */
proto.ipfs.Key.ED25519.prototype.setSize = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional RSA rsa = 1;
 * @return {?proto.ipfs.Key.RSA}
 */
proto.ipfs.Key.prototype.getRsa = function() {
  return /** @type{?proto.ipfs.Key.RSA} */ (
    jspb.Message.getWrapperField(this, proto.ipfs.Key.RSA, 1));
};


/** @param {?proto.ipfs.Key.RSA|undefined} value */
proto.ipfs.Key.prototype.setRsa = function(value) {
  jspb.Message.setOneofWrapperField(this, 1, proto.ipfs.Key.oneofGroups_[0], value);
};


proto.ipfs.Key.prototype.clearRsa = function() {
  this.setRsa(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ipfs.Key.prototype.hasRsa = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ED25519 ed25519 = 2;
 * @return {?proto.ipfs.Key.ED25519}
 */
proto.ipfs.Key.prototype.getEd25519 = function() {
  return /** @type{?proto.ipfs.Key.ED25519} */ (
    jspb.Message.getWrapperField(this, proto.ipfs.Key.ED25519, 2));
};


/** @param {?proto.ipfs.Key.ED25519|undefined} value */
proto.ipfs.Key.prototype.setEd25519 = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.ipfs.Key.oneofGroups_[0], value);
};


proto.ipfs.Key.prototype.clearEd25519 = function() {
  this.setEd25519(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ipfs.Key.prototype.hasEd25519 = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.ipfs.Key.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.ipfs.Key.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string id = 4;
 * @return {string}
 */
proto.ipfs.Key.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.ipfs.Key.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


goog.object.extend(exports, proto.ipfs);
